Repository virtueorg/ui, pull requests merged in 2023-10, with the labels that each got.

#12 Empty state
  src/lib/components/EmptyState/EmptyState.svelte
  src/lib/components/EmptyState/EmptyStateDescription.svelte
  src/lib/components/EmptyState/EmptyStateHeading.svelte
  src/lib/components/EmptyState/EmptyStateIllustration.svelte
  src/lib/components/EmptyState/EmptyStateTitle.svelte
  src/lib/components/EmptyState/index.ts
  src/lib/components/index.ts
  src/lib/illustrations/BoxIllustration.svelte
  src/lib/illustrations/index.ts
  src/lib/index.js
Labels: enhancement

#25 `SelectValue` is empty when no label is specified
  bun.lockb
  package.json
  src/lib/components/Select/SelectItem.svelte
Labels: bug

#31 Make Modal opaque
  src/lib/components/Modal/ModalContent.svelte
Labels: bug, enhancement
